### ISSUE TITLE
Error in the "vk_ray_tracing__simple_KHR" sample

### ISSUE THREAD

**Issue by pnt1614** [nvpro-samples/vk_raytracing_tutorial_KHR#17]
I try to run the "vk_ray_tracing__simple_KHR" sample but I always get an error about missing vkGetBufferDeviceAddress" dll. Is there anyway to fix this problem?

**Comment by mklefrancois** [comment]
I guess the issue you are seeing is due to the wrong Vulkan SDK. You need 1.2.162.0 and up, containing the official release for ray tracing. It is unfortunately not available for download and building one at the moment requires to be a Khronos member. I'm expecting a new SDK to be available before the end of the year (https://vulkan.lunarg.com/sdk/home). For the moment, you will also need the beta driver: https://developer.nvidia.com/vulkan-driver

**Comment by pnt1614** [comment]
Thanks for the reply, mklefrancois. I have installed the Vulkan SDK 1.2.162.0 and the latest beta driver for my RTX 2060 GPU card, and it fixes the "vkGetBufferDeviceAddress" problem. However, I still cannot run the sample due to the following error message:
" Could NOT locate mandatory extension 'VK_KHR_ray_tracing'
Skipping physical device GeForce RTX 2060
Physical devices found : OMG... NONE !!"

Do you know how to solve it? or Do I have to wait for the official release Nvidia driver?

**Comment by akeley98** [comment]
The VK_KHR_ray_tracing extension no longer exists as it has been split into three different extensions:

VK_KHR_acceleration_structure
VK_KHR_ray_tracing_pipeline
VK_KHR_ray_query

Can you check that you have the latest version of shared_sources and vk_raytracing_tutorial_KHR checked out and recompile?

**Comment by pnt1614** [comment]
I have cloned the latest version and everything works perfect.

Thanks guys.
