### ISSUE TITLE
VK_ERROR_LAYER_NOT_PRESENT on GTX1060

### ISSUE THREAD

**Issue by 2H0U** [nvpro-samples/vk_raytracing_tutorial_KHR#22]
Hi, I tried all ray tracing samples, and vkCreateInstance always return error message "VK_ERROR_LAYER_NOT_PRESENT". Please help. Thanks in advance. Below is my environment:
- GTX1060, driver 460.89
- Vulkan SDK 1.2.162
- Win10 pro 64
- VS 2019

**Comment by 2H0U** [comment]
It seem that GTX1060 (6GB) doesn't support ray query. VkPhysicalDeviceRayQueryFeaturesKHR::rayQuery is set to 0 after calling vkGetPhysicalDeviceFeatures2().

**Comment by 2H0U** [comment]
The old version vk_raytracing_tutorial works on GTX1060. It uses traceRaysNV instead of traceRaysKHR.
[https://github.com/nvpro-samples/vk_raytracing_tutorial](url)

**Comment by NeilBickford-NV** [comment]
Hi 2H0U! In case you're still having the issue with VK_ERROR_LAYER_NOT_PRESENT (this repository's code except for ray_tracing_rayquery should work on the GTX 1060 6GB, as all samples except for that one use ray queries), see if the discussion in https://github.com/nvpro-samples/vk_mini_path_tracer/issues/8 solves your problem. In that case:

- The most important indication was that the console log did not display `VK_LAYER_KHRONOS_validation` in the "Available Instance Layers :" section - is this what's happening in your case?
- This led to looking at https://www.asawicki.info/news_1683_vulkan_layers_dont_work_look_at_registry
- Looking at the `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ExplicitLayers` folder in the Windows Registry Editor, it turned out that on the developer's machine, there were leftover registry keys pointing to a version of the Vulkan SDK that had been removed (but which I'm guessing either hadn't been correctly uninstalled, or where maybe the installer had a bug). As a result, the Vulkan loader wasn't able to find the validation layer (because it was looking for it in the wrong place). I think the solution was to remove the registry keys from the old SDK.

**Comment by 2H0U** [comment]
Thanks for the reply. 
I was using CUDA toolkit 9 when the error occurred. After upgrading to CUDA toolkit 11, all samples except ray query run perfectly.
In my case, VK_LAYER_KHRONOS_validation was displayed in console log.

**Comment by NeilBickford-NV** [comment]
Ah, OK, glad you figured it out!
