### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by stefnotch** [nvpro-samples/vk_raytracing_tutorial_KHR#68]
The Nvidia site at https://developer.nvidia.com/rtx/raytracing/vkray links to

https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/

which doesn't seem to be the correct link anymore.

**Comment by NeilBickford-NV** [comment]
Ah, looks like I typo'ed the path to `markdeep.min.js` when I updated it to the new location; that's why `vkrt_tutorial.md.html` isn't embedding there. I'll have this fixed in just a moment!

**Comment by NeilBickford-NV** [comment]
OK, this should be fixed now! If you're still seeing `(insert vkrt_tutorial.md.html)` here, you may need to perform a hard reload of the page (Ctrl-Shift-R).

It turns out I forgot to update the `markdeep.min.js` path there, but it appeared to work when I tested it locally, because my browser served a cached copy of `markdeep.min.js` (which no longer existed at the old location).

Thanks for reporting this!

**Comment by stefnotch** [comment]
Awesome, thanks for fixing this!

And also thank you all for maintaining this very solid raytracing tutorial series. I'm currently having fun slowly working my way through them.

**Comment by mklefrancois** [comment]
Thank you for your kind words. If there are any topics that you feel are missing from the tutorial, please feel free to report them as a problem.
